# Generated by Django 4.2.16 on 2026-02-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom client (invité)"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email client (invité)"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rental", "Réservation location"),
                            ("part_order", "Commande pièce"),
                            ("transport_advance", "Avance transport international"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "rental_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Réservation"
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Commande pièce"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=5, verbose_name="Devise"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("stripe", "Carte bancaire (Stripe)"),
                            ("tmoney", "TMoney"),
                            ("flooz", "Flooz"),
                            ("cash_office", "Paiement au bureau"),
                        ],
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID transaction (externe)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Validé"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de facture",
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Note admin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
    ]
