# Generated by Django 4.2.16 on 2026-02-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=150, verbose_name="Nom du client"),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(
                        default="Lomé",
                        max_length=100,
                        verbose_name="Ville de destination",
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(
                        max_length=100, verbose_name="Pays d'origine du véhicule"
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ville d'origine"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Coût estimé (FCFA)",
                    ),
                ),
                (
                    "transport_note",
                    models.TextField(
                        blank=True,
                        verbose_name="Détails (délai, conditions, transporteur...)",
                    ),
                ),
                (
                    "customs_note",
                    models.CharField(
                        default="Le dédouanement n'est pas inclus dans ce devis.",
                        max_length=255,
                        verbose_name="Mention dédouanement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote_requested", "Devis demandé"),
                            ("quote_sent", "Devis envoyé au client"),
                            ("advance_paid", "Avance payée"),
                            ("in_transit", "En transit"),
                            ("arrived", "Arrivé au Togo"),
                            ("cancelled", "Annulé"),
                        ],
                        default="quote_requested",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Avance payée (FCFA)",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Note interne admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_requests",
                        to="catalog.vehicle",
                        verbose_name="Véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de transport",
                "verbose_name_plural": "Demandes de transport",
                "ordering": ["-created_at"],
            },
        ),
    ]
