# Generated by Django 4.2.16 on 2026-02-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nom du transporteur"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Contact"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transporteur",
                "verbose_name_plural": "Transporteurs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=150, verbose_name="Nom du client"),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(
                        default="Lomé",
                        max_length=100,
                        verbose_name="Ville de destination",
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(max_length=100, verbose_name="Pays d'origine"),
                ),
                (
                    "origin_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ville d'origine"
                    ),
                ),
                (
                    "vehicle_weight_kg",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Poids du véhicule (kg)"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Coût estimé (FCFA)",
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Coût final validé par l'admin (FCFA)",
                    ),
                ),
                (
                    "advance_required",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Avance requise (FCFA)",
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Avance payée (FCFA)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote_requested", "Devis demandé"),
                            ("quote_sent", "Devis envoyé au client"),
                            ("advance_paid", "Avance payée — en attente chargement"),
                            ("loading", "Chargement en cours"),
                            ("in_transit", "En transit"),
                            ("arrived_port", "Arrivé au port de Lomé"),
                            ("customs", "En cours de dédouanement"),
                            ("delivered", "Livré au client"),
                            ("cancelled", "Annulé"),
                        ],
                        default="quote_requested",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "customs_note",
                    models.CharField(
                        default="Le dédouanement n'est pas inclus dans ce devis.",
                        max_length=255,
                        verbose_name="Mention dédouanement",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Note interne admin"),
                ),
                (
                    "client_note",
                    models.TextField(
                        blank=True, verbose_name="Message visible par le client"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="logistics.transporter",
                        verbose_name="Transporteur assigné",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_requests",
                        to="catalog.vehicle",
                        verbose_name="Véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de transport",
                "verbose_name_plural": "Demandes de transport",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la zone"),
                ),
                (
                    "countries",
                    models.TextField(
                        help_text="Ex: France\nAllemagne\nBelgique",
                        verbose_name="Pays inclus (un par ligne)",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix de base (FCFA)",
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Supplément par kg (FCFA)",
                    ),
                ),
                (
                    "delay_days_min",
                    models.PositiveIntegerField(verbose_name="Délai minimum (jours)"),
                ),
                (
                    "delay_days_max",
                    models.PositiveIntegerField(verbose_name="Délai maximum (jours)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Notes (conditions, restrictions...)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone tarifaire",
                "verbose_name_plural": "Zones tarifaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote_requested", "Devis demandé"),
                            ("quote_sent", "Devis envoyé au client"),
                            ("advance_paid", "Avance payée — en attente chargement"),
                            ("loading", "Chargement en cours"),
                            ("in_transit", "En transit"),
                            ("arrived_port", "Arrivé au port de Lomé"),
                            ("customs", "En cours de dédouanement"),
                            ("delivered", "Livré au client"),
                            ("cancelled", "Annulé"),
                        ],
                        max_length=20,
                        verbose_name="Statut atteint",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'étape"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Lieu (port, ville...)"
                    ),
                ),
                (
                    "reached_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Atteint le"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="logistics.transportrequest",
                        verbose_name="Demande de transport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de transport",
                "verbose_name_plural": "Étapes de transport",
                "ordering": ["reached_at"],
            },
        ),
        migrations.AddField(
            model_name="transportrequest",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="logistics.transportzone",
                verbose_name="Zone tarifaire détectée",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="transporters",
                to="logistics.transportzone",
                verbose_name="Zones couvertes",
            ),
        ),
    ]
