# Generated by Django 4.2.16 on 2026-02-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Marque"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Marque",
                "verbose_name_plural": "Marques",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Nom de la pièce"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Neuf"), ("used", "Occasion")],
                        default="new",
                        max_length=10,
                        verbose_name="État",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix (FCFA)"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité en stock"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "En stock"),
                            ("out_of_stock", "Rupture de stock"),
                        ],
                        default="in_stock",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_local",
                    models.BooleanField(
                        default=True,
                        verbose_name="Disponible au Togo (livraison rapide)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mise en avant"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compatible_brands",
                    models.ManyToManyField(
                        blank=True,
                        to="catalog.brand",
                        verbose_name="Marques compatibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce détachée",
                "verbose_name_plural": "Pièces détachées",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'annonce"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "Voiture"), ("moto", "Moto")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "En vente"), ("rental", "En location")],
                        max_length=10,
                        verbose_name="Type d'annonce",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kilométrage (km)"
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("petrol", "Essence"),
                            ("diesel", "Diesel"),
                            ("electric", "Électrique"),
                            ("hybrid", "Hybride"),
                        ],
                        max_length=20,
                        verbose_name="Carburant",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("manual", "Manuelle"), ("automatic", "Automatique")],
                        max_length=20,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Couleur"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Neuf"), ("used", "Occasion")],
                        max_length=10,
                        verbose_name="État",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix (vente en FCFA)",
                    ),
                ),
                (
                    "rental_price_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix de location par jour (FCFA)",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("local", "Au Togo"),
                            ("international", "À l'étranger"),
                        ],
                        default="local",
                        max_length=15,
                        verbose_name="Origine",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "country",
                    models.CharField(
                        default="Togo", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "transport_included",
                    models.BooleanField(
                        default=False, verbose_name="Frais de transport inclus"
                    ),
                ),
                (
                    "transport_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimation frais de transport (FCFA)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("reserved", "Réservé"),
                            ("sold", "Vendu"),
                            ("unavailable", "Indisponible"),
                        ],
                        default="available",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mise en avant"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.brand",
                        verbose_name="Marque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Modèle")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle",
                "verbose_name_plural": "Modèles",
                "ordering": ["name"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="VehicleMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Vidéo")],
                        default="photo",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="vehicles/media/")),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="Photo principale"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média véhicule",
                "verbose_name_plural": "Médias véhicules",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.vehiclemodel",
                verbose_name="Modèle",
            ),
        ),
        migrations.CreateModel(
            name="SparePartMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="parts/media/")),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.sparepart",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="sparepart",
            name="compatible_models",
            field=models.ManyToManyField(
                blank=True,
                to="catalog.vehiclemodel",
                verbose_name="Modèles compatibles",
            ),
        ),
    ]
