# Generated by Django 4.2.16 on 2026-02-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom (invité)"
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone (invité)"
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email (invité)"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix unitaire (FCFA)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix total (FCFA)",
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("home", "Livraison à domicile"),
                            ("pickup", "Retrait sur place"),
                        ],
                        default="home",
                        max_length=10,
                        verbose_name="Mode de livraison",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "estimated_delivery",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Délai estimé (ex: 1h, 24h)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de confirmation"),
                            ("confirmed", "Confirmée"),
                            ("preparing", "En préparation"),
                            ("out_for_delivery", "En cours de livraison"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Note admin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="part_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte client (optionnel)",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="catalog.sparepart",
                        verbose_name="Pièce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande de pièce",
                "verbose_name_plural": "Commandes de pièces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("pickup", "Retrait sur place"),
                            ("delivery", "Livraison à domicile"),
                        ],
                        default="pickup",
                        max_length=10,
                        verbose_name="Mode de récupération",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix/jour (FCFA)"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix total (FCFA)",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_kyc", "En attente de vérification KYC"),
                            ("pending_payment", "En attente de paiement"),
                            ("confirmed", "Confirmée"),
                            ("active", "En cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending_kyc",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Note admin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to="catalog.vehicle",
                        verbose_name="Véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "sender_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Lu par l'admin"),
                ),
                (
                    "admin_reply",
                    models.TextField(blank=True, verbose_name="Réponse de l'admin"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Répondu le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="catalog.sparepart",
                        verbose_name="Pièce concernée",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="catalog.vehicle",
                        verbose_name="Véhicule concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
